import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { RootProvider } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import { ErrorToastProvider } from "@/components/providers/error";
import { NotificationToastProvider } from "@/components/providers/notification";

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.className} antialiased bg-gray-100`}>
                <RootProvider>
                    {children}
                    <Toaster position="top-right" closeButton />
                    <ErrorToastProvider />
                    <NotificationToastProvider />
                </RootProvider>
            </body>
        </html>
    );
}
